# Generated by Django 5.0.7 on 2024-08-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_telegrammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammember',
            name='username',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='telegrammember',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
