# Generated by Django 5.1 on 2024-08-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_telegrammember_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordMember',
            fields=[
                ('member_id', models.CharField(db_column='member_id', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('bot', models.BooleanField(default=False)),
                ('nick', models.CharField(blank=True, max_length=100, null=True)),
                ('cached_at', models.DateTimeField()),
            ],
        ),
    ]
