# Generated by Django 5.1.4 on 2024-12-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0007_joindaaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joindaaccount',
            name='discord_member_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='joindaaccount',
            name='email',
            field=models.CharField(primary_key=True, serialize=False, unique=True),
        ),
    ]
