# Generated by Django 5.2.4 on 2025-07-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helper", "0008_alter_joindaaccount_discord_member_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="campaign",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
